// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCugOc5L35ahIwWGNeV1W9wwToKkWxlL2c',
    appId: '1:663178460202:web:3ad5a2552ef771bb6d1753',
    messagingSenderId: '663178460202',
    projectId: 'instagram-clone-cf0db',
    authDomain: 'instagram-clone-cf0db.firebaseapp.com',
    storageBucket: 'instagram-clone-cf0db.firebasestorage.app',
    measurementId: 'G-LDVRYRFTSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJJOemavzsyLEwxbeOLAi7PuU0NWDxdy0',
    appId: '1:663178460202:android:da140cabf9dd886a6d1753',
    messagingSenderId: '663178460202',
    projectId: 'instagram-clone-cf0db',
    storageBucket: 'instagram-clone-cf0db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaWoKeZGfdzdp7FfXKOp5t40XKBIMWs-U',
    appId: '1:663178460202:ios:a0f3c064faeb625c6d1753',
    messagingSenderId: '663178460202',
    projectId: 'instagram-clone-cf0db',
    storageBucket: 'instagram-clone-cf0db.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaWoKeZGfdzdp7FfXKOp5t40XKBIMWs-U',
    appId: '1:663178460202:ios:a0f3c064faeb625c6d1753',
    messagingSenderId: '663178460202',
    projectId: 'instagram-clone-cf0db',
    storageBucket: 'instagram-clone-cf0db.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCugOc5L35ahIwWGNeV1W9wwToKkWxlL2c',
    appId: '1:663178460202:web:3eacc53986d8403d6d1753',
    messagingSenderId: '663178460202',
    projectId: 'instagram-clone-cf0db',
    authDomain: 'instagram-clone-cf0db.firebaseapp.com',
    storageBucket: 'instagram-clone-cf0db.firebasestorage.app',
    measurementId: 'G-G5P1JS4S15',
  );
}
